local ok, fzf = pcall(require, "fzf-lua")
if not ok then return end
fzf.setup { "myprofile" }

vim.keymap.set("!a", "W", "w")
vim.keymap.set("!a", "Q", "q")
vim.keymap.set("", "x", '"_x')
vim.keymap.set("n", "n", "nzz")
vim.keymap.set("n", "N", "Nzz")
vim.keymap.set("s", "<BS>", "<C-o>s")
vim.keymap.set("i", "<C-c>", "<Esc>")
vim.keymap.set("n", "r<C-c>", "<Esc>")
vim.keymap.set("x", "/", "<Esc>/\\%V")
vim.keymap.set("", "<leader>y", [["+y]])
vim.keymap.set("n", "<C-n>", "<cmd>cn<cr>")
vim.keymap.set("n", "<C-p>", "<cmd>cp<cr>")
vim.keymap.set("n", "<C-q>", "<cmd>cexpr []<cr>")
vim.keymap.set("n", "<leader>q", "<cmd>copen<cr>")
vim.keymap.set("s", "<Tab>", [[:vim.snippet.jump(1)]])
vim.keymap.set("s", "<S-Tab>", [[:vim.snippet.jump(-1)]])
vim.keymap.set("i", "<C-b>", "<C-x><C-n>")
vim.keymap.set("i", "<C-f>", "<C-x><C-f>")
vim.keymap.set("i", "<C-l>", "<C-x><C-o>")
vim.keymap.set("n", "<C-x>", "<C-W>5>")
vim.keymap.set("n", "<C-z>", "<C-W>5<")
vim.keymap.set("t", "<esc>", "<c-\\><c-n>")
vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv")
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv")
vim.keymap.set("n", "\\", "<cmd>tabnext<cr>")
vim.keymap.set("n", "<leader>e", "<cmd>Ex<cr>")
vim.keymap.set("n", "|", "<cmd>tabprevious<cr>")
vim.keymap.set("n", "<leader>fi", "<cmd>!file %/<cWORD><cr>")
vim.keymap.set("n", "<leader>`", "<cmd>sp<bar>term<cr><c-w>J<cmd>resize15<cr>i")
vim.keymap.set("n", "<leader>re", [[:%s/\<<C-r><C-w>\>/<C-r><C-w>/gIc<Left><Left><Left><Left>]])
vim.keymap.set("n", "K", vim.lsp.buf.hover)
vim.keymap.set("n", "gd", vim.lsp.buf.definition)
vim.keymap.set("n", "gD", vim.lsp.buf.declaration)
vim.keymap.set("n", "I", vim.diagnostic.open_float)
vim.keymap.set("n", "<leader>lr", vim.lsp.buf.rename)
vim.keymap.set("n", "<leader>fb", vim.lsp.buf.format)
vim.keymap.set("n", "<leader>u", vim.cmd.UndotreeToggle)
vim.keymap.set("n", "<leader>/", fzf.builtin)
vim.keymap.set("n", "<leader>dd", fzf.diagnostics_document)
vim.keymap.set("n", "<leader>ff", fzf.files)
vim.keymap.set("n", "<leader>fs", fzf.live_grep_native)
vim.keymap.set("n", "<leader>sw", fzf.grep_cword)
vim.keymap.set("n", "<leader>ht", fzf.helptags)
vim.keymap.set("n", "<leader>bb", fzf.buffers)
vim.keymap.set("n", "<leader>hm", fzf.manpages)
vim.keymap.set("n", "<leader>co", fzf.colorschemes)
vim.keymap.set("n", "<leader>ls", fzf.lsp_document_symbols)
vim.keymap.set("n", "<leader>ac", fzf.lsp_code_actions)
vim.keymap.set("n", "<leader>ll", fzf.lsp_references)
vim.keymap.set("n", "<leader>gf", fzf.git_files)
vim.keymap.set("n", "<leader>gs", fzf.git_status)
vim.keymap.set("n", "<leader>gb", fzf.git_blame)
vim.keymap.set("n", "<leader>gt", fzf.git_branches)
vim.keymap.set("n", "<leader>gc", fzf.git_commits)
