local utils = require "config.utils"

vim.keymap.set("i", "<C-b>", "<C-x><C-n>")
vim.keymap.set("i", "<C-f>", "<C-x><C-f>")
vim.keymap.set("i", "<C-l>", "<C-x><C-o>")
vim.keymap.set({ "i", "n" }, "<C-s>", utils.toggle_language)
vim.keymap.set("n", "<C-d>", "<C-d>zz")
vim.keymap.set("n", "\\", "<cmd>tabnext<cr>")
vim.keymap.set("n", "|", "<cmd>tabprevious<cr>")
vim.keymap.set("n", "<C-n>", utils.list_next)
vim.keymap.set("n", "<C-p>", utils.list_prev)
vim.keymap.set("n", "<C-q>", utils.clear_qf)
vim.keymap.set("n", "<C-Tab>", "<c-6>")
vim.keymap.set("n", "<C-u>", "<C-u>zz")
vim.keymap.set("n", "<C-x>", "<C-W>5>")
vim.keymap.set("n", "<C-z>", "<C-W>5<")
vim.keymap.set("n", "gt", "<nop>")
vim.keymap.set("n", "<leader>`", "<cmd>sp<bar>term<cr><c-w>J<cmd>resize10<cr>i")
vim.keymap.set("n", "<leader>e", utils.toggle_netrw)
vim.keymap.set("n", "<leader>q", utils.toggle_quickfix)
vim.keymap.set("n", "<leader>re", [[:%s/\<<C-r><C-w>\>/<C-r><C-w>/gIc<Left><Left><Left><Left>]])
vim.keymap.set("n", "';", "<nop>")
vim.keymap.set("n", "Q", "<nop>")
vim.keymap.set({ "n", "v" }, "<leader>y", [["+y]])
vim.keymap.set({ "n", "v" }, "x", '"_x')
vim.keymap.set("t", "<esc>", "<c-\\><c-n>")
vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv")
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv")
vim.keymap.set("x", "p", 'p<cmd>let @+=@0<CR><cmd>let @"=@0<CR>')
