local utils = require "config.utils"

vim.keymap.set("n", "Q", "<nop>", nil)
vim.keymap.set("n", "';", "<nop>", nil)
vim.keymap.set("n", "gt", "<nop>", nil)
vim.keymap.set("n", "<space>m", utils.toggle_file_qf, nil)
vim.keymap.set("n", "<C-n>", utils.list_next, nil)
vim.keymap.set("n", "<C-p>", utils.list_prev, nil)
vim.keymap.set("n", "<leader>q", utils.toggle_quickfix, nil)
vim.keymap.set("n", '<leader>e', utils.toggle_netrw, nil)
vim.keymap.set("n", '<leader>o', ':tabedit %:p:h<CR>', nil)
vim.keymap.set("n", "n", "nzzzv", nil)
vim.keymap.set("n", "N", "Nzzzv", nil)
vim.keymap.set("t", "<esc>", "<c-\\><c-n>", nil)
vim.keymap.set("n", "<leader>`", "<cmd>sp<bar>term<cr><c-w>J<cmd>resize10<cr>i", nil)
vim.keymap.set("n", "<leader>re", [[:%s/\<<C-r><C-w>\>/<C-r><C-w>/gIc<Left><Left><Left><Left>]], nil)
vim.keymap.set({ "n", "v" }, "<leader>y", [["+y]], nil)
vim.keymap.set({ "n", "v" }, "x", '"_x', nil)
vim.keymap.set("x", "p", 'p<cmd>let @+=@0<CR><cmd>let @"=@0<CR>', nil)
vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv", nil)
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv", nil)
vim.keymap.set("n", "<C-d>", "<C-d>zz", nil)
vim.keymap.set("n", "<C-u>", "<C-u>zz", nil)
vim.keymap.set("n", "<C-q>", utils.clear_qf, nil)
vim.keymap.set("n", "<C-j>", "<C-W>j", nil)
vim.keymap.set("n", "<C-k>", "<C-W>k", nil)
vim.keymap.set("n", "<C-h>", "<C-W>h", nil)
vim.keymap.set("n", "<C-l>", "<C-W>l", nil)
vim.keymap.set("n", "<C-z>", "<C-W>5<", nil)
vim.keymap.set("n", "<C-x>", "<C-W>5>", nil)
vim.keymap.set("n", "\\", "<cmd>tabnext<cr>", nil)
vim.keymap.set("n", "|", "<cmd>tabprevious<cr>", nil)
vim.keymap.set("n", "<space>v", utils.vimgrep, nil)
vim.keymap.set({ "i", "n" }, "<c-s>", utils.toggle_language, nil)
-- vim.keymap.set("n", "<space>b", [[:buffer ]], nil)
vim.keymap.set("i", "<C-b>", "<C-x><C-n>", nil)
vim.keymap.set("i", "<C-l>", "<C-x><C-o>", nil)
