local map = function(mode, keys, func, desc, silent)
  vim.keymap.set(mode, keys, func, { desc = desc, silent = silent })
end

map("n", "<leader>pv", vim.cmd.Ex, "Neovim: Open Netrw", true)
map({ "n", "v" }, "<leader>y", [["+y]], "Neovim: Copy to system clipboard", true)
map("n", "<leader>r", [[:%s/\<<C-r><C-w>\>/<C-r><C-w>/gIc<Left><Left><Left><Left>]], "Regex: Replace word", false)
map('n', '<leader>gr', '<cmd>set spelllang=polytonic<cr>', 'Neovim: Set spellchecking language to Greek', false)
map("v", "J", ":m '>+1<CR>gv=gv", nil, true)
map("v", "K", ":m '<-2<CR>gv=gv", nil, true)
map("n", "<C-d>", "<C-d>zz", nil, true)
map("n", "<C-u>", "<C-u>zz", nil, true)
map("n", "<C-m>", "<nop>", nil, true)
map("n", "q:", "<nop>", nil, true)
map("n", "Q", "<nop>", nil, true)
map({ 'n', 'v' }, 'x', '"_x', nil, true)
map('t', '<esc>', '<c-\\><c-n>', nil, false)
map('n', '<leader>q', ':sp<bar>term<cr><c-w>J:resize10<cr>', "Neovim: Launch terminal as a split", true)
