vim.opt_local.expandtab = true
vim.opt_local.shiftwidth = 2
vim.opt_local.softtabstop = 2
vim.opt_local.tabstop = 2
vim.opt_local.wrap = true
vim.opt_local.linebreak = true
vim.opt_local.scrolloff = 0
vim.opt_local.scrolloff = 0
vim.opt_local.nu = true
vim.opt_local.relativenumber = false
-- vim.opt_local.commentstring = "<!-- %s -->"
