#!/bin/bash

if [ $# -ne 1 ]; then
    echo "Usage: $0 <pid>"
    exit 1
fi

pid=$1

while true; do
    vmrss_kb=$(ps -o vsz= -p $pid)
    vmrss_mb=$(echo "scale=3; $vmrss_kb / 1024" | bc)
    echo "Memory usage (vmrss) of PID $pid: $vmrss_mb MB"
    sleep 1
done

